### ISSUE TITLE
More flexible pattern to find test projects

### ISSUE THREAD

**Issue by FlorianHockmann** [secana/CakeApp#1]
I always name my test projects `MyApplication_UnitTest` and `MyApplication_IntegrationTest`, but the Cake script currently only allows test projects that end on `_Test`.
How about using a more flexible pattern to find test projects like `*Test` (instead of the current `*_Test`)? 

This should still avoid the problem with test util projects that don't contain any tests themselves as their names usually don't end on `Test`.

If you like, I can create a pull request for this (trivial) change.

**Comment by secana** [comment]
Good point. I've updated the code to match on *Test
Updated in NuGet package version 1.0.2
